import type {
  CustomerType,
  CustomerTypeId,
  DailyEvent,
  EventId,
  Product,
  ProductCategory,
  ProductCategoryId,
  ProductId,
  ShopStage,
  Supplier,
  SupplierId,
  Upgrade,
  UpgradeId,
} from './types';

export const productCategories: Record<ProductCategoryId, ProductCategory> = {
  bakery: {
    id: 'bakery',
    name: '烘焙',
    description: '早晨和放学后最容易被顺手带走的温暖小食。',
  },
  drink: {
    id: 'drink',
    name: '饮品',
    description: '冰柜和热饮台撑起小店最稳定的人气。',
  },
  daily: {
    id: 'daily',
    name: '日用品',
    description: '街坊临时需要时最依赖的基础货架。',
  },
  meal: {
    id: 'meal',
    name: '轻食',
    description: '上班族和夜归人的主力消费品类。',
  },
  stationery: {
    id: 'stationery',
    name: '文具',
    description: '学生常看的低价高频小物。',
  },
  lifestyle: {
    id: 'lifestyle',
    name: '生活小物',
    description: '让小店更有记忆点的氛围商品。',
  },
};

export const products: Record<ProductId, Product> = {
  bread: {
    id: 'bread',
    categoryId: 'bakery',
    name: '晨烤面包',
    description: '街坊早晨最常带走的小食，稳定又亲切。',
    unitCost: 4,
    unitPrice: 8,
    baseDemand: 8,
    comfortBonus: 1,
  },
  redBeanBun: {
    id: 'redBeanBun',
    categoryId: 'bakery',
    name: '红豆面包',
    description: '甜味更足，学生和老街坊都容易多拿一个。',
    unitCost: 5,
    unitPrice: 10,
    baseDemand: 6,
    comfortBonus: 1,
    unlockCondition: { reputation: 6 },
  },
  croissant: {
    id: 'croissant',
    categoryId: 'bakery',
    name: '奶油可颂',
    description: '利润高一点，也更吃店铺氛围。',
    unitCost: 7,
    unitPrice: 14,
    baseDemand: 4,
    comfortBonus: 2,
    unlockCondition: { decorLevel: 2 },
  },
  drink: {
    id: 'drink',
    categoryId: 'drink',
    name: '玻璃瓶饮料',
    description: '冰柜里的小小快乐，天气越热越受欢迎。',
    unitCost: 3,
    unitPrice: 7,
    baseDemand: 10,
    comfortBonus: 0,
  },
  milk: {
    id: 'milk',
    categoryId: 'drink',
    name: '鲜牛奶',
    description: '学生和老街坊都愿意顺手带走的温和新品。',
    unitCost: 5,
    unitPrice: 10,
    baseDemand: 6,
    comfortBonus: 1,
    unlockCondition: { reputation: 8 },
  },
  juice: {
    id: 'juice',
    categoryId: 'drink',
    name: '鲜榨果汁',
    description: '更贵也更讨喜，适合声望起来后上架。',
    unitCost: 8,
    unitPrice: 16,
    baseDemand: 4,
    comfortBonus: 2,
    unlockCondition: { reputation: 20 },
  },
  daily: {
    id: 'daily',
    categoryId: 'daily',
    name: '日用杂货',
    description: '利润高但需求慢热，适合有回头客的小店。',
    unitCost: 9,
    unitPrice: 17,
    baseDemand: 5,
    comfortBonus: 2,
  },
  tissue: {
    id: 'tissue',
    categoryId: 'daily',
    name: '纸巾',
    description: '不起眼但稳定，雨天和夜晚尤其容易被想起。',
    unitCost: 4,
    unitPrice: 8,
    baseDemand: 6,
    comfortBonus: 0,
    unlockCondition: { reputation: 5 },
  },
  umbrella: {
    id: 'umbrella',
    categoryId: 'daily',
    name: '折叠雨伞',
    description: '雨天的救急商品，单价高但需求波动大。',
    unitCost: 14,
    unitPrice: 28,
    baseDemand: 2,
    comfortBonus: 0,
    unlockCondition: { reputation: 18 },
  },
  lunch: {
    id: 'lunch',
    categoryId: 'meal',
    name: '热便当',
    description: '上班族赶时间时最可靠的一餐，利润也更高。',
    unitCost: 12,
    unitPrice: 23,
    baseDemand: 7,
    comfortBonus: 1,
    unlockCondition: { shopLevel: 2 },
  },
  riceBall: {
    id: 'riceBall',
    categoryId: 'meal',
    name: '饭团',
    description: '便宜、顶饱、出货快，是轻食类的入门商品。',
    unitCost: 6,
    unitPrice: 12,
    baseDemand: 6,
    comfortBonus: 0,
    unlockCondition: { reputation: 10 },
  },
  oden: {
    id: 'oden',
    categoryId: 'meal',
    name: '关东煮',
    description: '夜归人会被热气吸引，舒适度越高越好卖。',
    unitCost: 10,
    unitPrice: 20,
    baseDemand: 4,
    comfortBonus: 3,
    unlockCondition: { shopLevel: 2, decorLevel: 2 },
  },
  stationery: {
    id: 'stationery',
    categoryId: 'stationery',
    name: '小文具',
    description: '放学后会被翻看的笔、本子和便利贴。',
    unitCost: 4,
    unitPrice: 9,
    baseDemand: 4,
    comfortBonus: 0,
    unlockCondition: { reputation: 14 },
  },
  notebook: {
    id: 'notebook',
    categoryId: 'stationery',
    name: '作业本',
    description: '学生客群多时很稳，利润不高但回转快。',
    unitCost: 3,
    unitPrice: 7,
    baseDemand: 5,
    comfortBonus: 0,
    unlockCondition: { reputation: 12 },
  },
  pen: {
    id: 'pen',
    categoryId: 'stationery',
    name: '中性笔',
    description: '价格低、需求细碎，是文具货架的基础款。',
    unitCost: 2,
    unitPrice: 5,
    baseDemand: 6,
    comfortBonus: 0,
    unlockCondition: { reputation: 9 },
  },
  flower: {
    id: 'flower',
    categoryId: 'lifestyle',
    name: '门口鲜花',
    description: '店里足够舒服时，鲜花会成为最温柔的额外收入。',
    unitCost: 10,
    unitPrice: 22,
    baseDemand: 3,
    comfortBonus: 4,
    unlockCondition: { decorLevel: 3 },
  },
  postcard: {
    id: 'postcard',
    categoryId: 'lifestyle',
    name: '手写贺卡',
    description: '小而有情绪价值，适合有声望的小店。',
    unitCost: 4,
    unitPrice: 10,
    baseDemand: 3,
    comfortBonus: 2,
    unlockCondition: { reputation: 16 },
  },
  plant: {
    id: 'plant',
    categoryId: 'lifestyle',
    name: '小盆栽',
    description: '装饰等级越高越容易被注意到。',
    unitCost: 12,
    unitPrice: 26,
    baseDemand: 2,
    comfortBonus: 5,
    unlockCondition: { decorLevel: 4 },
  },
};

export const suppliers: Record<SupplierId, Supplier> = {
  directMarket: {
    id: 'directMarket',
    name: '街口临采',
    description: '不挑品类，价格普通，适合临时补缺货。',
    suppliedCategories: ['bakery', 'drink', 'daily', 'meal', 'stationery', 'lifestyle'],
    generalDiscount: 0,
    categoryDiscounts: {},
  },
  morningBakery: {
    id: 'morningBakery',
    name: '清晨烘焙坊',
    description: '主供烘焙和饮品，面包类价格更合适。',
    suppliedCategories: ['bakery', 'drink'],
    generalDiscount: 0,
    categoryDiscounts: {
      bakery: 0.1,
    },
  },
  communityWholesale: {
    id: 'communityWholesale',
    name: '社区批发站',
    description: '主供日用品和文具，适合稳定补货。',
    suppliedCategories: ['daily', 'stationery'],
    generalDiscount: 0.05,
    categoryDiscounts: {},
    unlockCondition: { reputation: 10 },
  },
  nightDepot: {
    id: 'nightDepot',
    name: '夜间便利仓',
    description: '主供轻食和生活小物，适合晚间客群。',
    suppliedCategories: ['meal', 'lifestyle'],
    generalDiscount: 0,
    categoryDiscounts: {
      meal: 0.08,
    },
    unlockCondition: { shopLevel: 2 },
  },
};

export const upgrades: Record<UpgradeId, Upgrade> = {
  shelf: {
    id: 'shelf',
    name: '木质货架',
    description: '让商品摆得更从容，也能减少缺货。',
    baseCost: 90,
    maxLevel: 5,
  },
  checkout: {
    id: 'checkout',
    name: '收银台',
    description: '缩短排队时间，顾客离开时心情更轻松。',
    baseCost: 120,
    maxLevel: 5,
  },
  decor: {
    id: 'decor',
    name: '店内装饰',
    description: '灯光、绿植和手写价签会让小店更有人情味。',
    baseCost: 100,
    maxLevel: 5,
  },
};

export const customerTypes: Record<CustomerTypeId, CustomerType> = {
  student: {
    id: 'student',
    name: '学生',
    description: '放学路上会先看烘焙、饮品和文具，对价格和缺货很敏感。',
    demandMultipliers: { bread: 1.15, redBeanBun: 1.25, drink: 1.1, milk: 1.15, stationery: 1.25, notebook: 1.25, pen: 1.3 },
    categoryMultipliers: { bakery: 1.25, drink: 1.2, stationery: 1.35 },
    serviceSensitivity: 0.7,
    comfortSensitivity: 0.5,
    stockoutSensitivity: 1.1,
  },
  office: {
    id: 'office',
    name: '上班族',
    description: '时间紧，喜欢饮品和轻食，排队太久会明显不满。',
    demandMultipliers: { drink: 1.15, lunch: 1.35, riceBall: 1.25 },
    categoryMultipliers: { drink: 1.2, meal: 1.45 },
    serviceSensitivity: 1.45,
    comfortSensitivity: 0.6,
    stockoutSensitivity: 1,
  },
  neighbor: {
    id: 'neighbor',
    name: '老街坊',
    description: '更看重舒适和熟悉感，常买日用品、饮品和生活小物。',
    demandMultipliers: { daily: 1.2, milk: 1.15, tissue: 1.2, flower: 1.1 },
    categoryMultipliers: { daily: 1.35, drink: 1.1, lifestyle: 1.2 },
    serviceSensitivity: 0.8,
    comfortSensitivity: 1.5,
    stockoutSensitivity: 0.8,
  },
  night: {
    id: 'night',
    name: '夜归人',
    description: '晚归时会买轻食、日用品和饮品，缺货会让他们很失望。',
    demandMultipliers: { daily: 1.15, lunch: 1.2, oden: 1.35, umbrella: 1.15 },
    categoryMultipliers: { meal: 1.35, daily: 1.2, drink: 1.1 },
    serviceSensitivity: 0.9,
    comfortSensitivity: 0.8,
    stockoutSensitivity: 1.55,
  },
};

export const dailyEvents: Record<EventId, DailyEvent> = {
  rainy: {
    id: 'rainy',
    name: '雨天',
    description: '街上人少了一些，但进门的人更愿意买饮品、热食和雨伞。',
    demandMultipliers: { drink: 1.1, lunch: 1.15, oden: 1.25, umbrella: 2.2 },
    categoryMultipliers: { bakery: 0.85, daily: 1.1, meal: 1.15 },
    satisfactionBonus: 0,
    reputationMultiplier: 1,
  },
  schoolRush: {
    id: 'schoolRush',
    name: '放学后',
    description: '附近学校放学，小店门口热闹起来。',
    demandMultipliers: { bread: 1.2, drink: 1.15, milk: 1.15, stationery: 1.25, notebook: 1.35, pen: 1.35 },
    categoryMultipliers: { bakery: 1.2, drink: 1.15, stationery: 1.35 },
    customerBias: 'student',
    satisfactionBonus: 0,
    reputationMultiplier: 1,
  },
  supplierDiscount: {
    id: 'supplierDiscount',
    name: '供应商打折',
    description: '供应商临时让利，今天进货更划算。',
    demandMultipliers: {},
    satisfactionBonus: 0,
    reputationMultiplier: 1,
  },
  neighborRecommend: {
    id: 'neighborRecommend',
    name: '街坊推荐',
    description: '熟客把小店推荐给了邻居，今天的口碑涨得更快。',
    demandMultipliers: { daily: 1.1, milk: 1.1, flower: 1.1 },
    categoryMultipliers: { daily: 1.1, lifestyle: 1.15 },
    customerBias: 'neighbor',
    satisfactionBonus: 1,
    reputationMultiplier: 1.5,
  },
  queueComplaint: {
    id: 'queueComplaint',
    name: '排队抱怨',
    description: '顾客对排队更敏感，服务不足会拉低满意度。',
    demandMultipliers: {},
    customerBias: 'office',
    satisfactionBonus: -2,
    reputationMultiplier: 0.9,
  },
};

export const shopStages: ShopStage[] = [
  {
    level: 1,
    name: '旧街角小店',
    description: '门铃还有些生锈，但每天都有熟客路过。',
    requiredCash: 0,
    requiredReputation: 0,
  },
  {
    level: 2,
    name: '小而温暖的便利店',
    description: '货架整齐了起来，晚归的人也愿意多停一会儿。',
    requiredCash: 420,
    requiredReputation: 18,
  },
  {
    level: 3,
    name: '社区人气小店',
    description: '这里开始成为街坊约定俗成的补给站。',
    requiredCash: 980,
    requiredReputation: 45,
  },
];
